const cartTypes = {
  TOGGLE_CART_DROPDOWN: "TOGGLE_CART_DROPDOWN",
  ADD_CART_ITEM: "ADD_CART_ITEM",
  REMOVE_CART_ITEM: "REMOVE_CART_ITEM",
  DECREASE_CART_ITEM: "DECREASE_CART_ITEM",
  CLEAR_CART: "CLEAR_CART"
};

export default cartTypes;
