const types = {
  GOOGLE_SIGN_IN_START: "GOOGLE_SIGN_IN_START",
  EMAIL_SIGN_IN_START: "EMAIL_SIGN_IN_START",
  SIGN_IN_FAIL: "SIGN_IN_FAIL",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  REMOVE_ERROR: "REMOVE_ERROR",
  SIGN_OUT_START: "SIGN_OUT_START",
  SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
  SIGN_OUT_FAIL: "SIGN_OUT_FAIL",
  CHECK_USER_STATE: "CHECK_USER_STATE",
  SIGN_UP_START: "SIGN_UP_START",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
  SIGN_UP_FAIL: "SIGN_UP_FAIL"
};

export default types;
